# Uncomment the next line to define a global platform for your project
# platform :ios, ’8.0’

target 'NativeStarterKit' do
  
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'


  pod ‘Yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'BatchedBridge', # REMOVE THIS if you use RN 0.54+
  ]

  pod 'react-native-maps', path: rn_maps_path

  pod 'Firebase/Core'

end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end


target 'NativeStarterKit-tvOSTests' do
  inherit! :search_paths
  # Pods for testing
end


target 'NativeStarterKitTests' do
  inherit! :search_paths
  # Pods for testing
end